import type { Metadata } from "next";
import Sidebar from "@/components/layouts/Sidebar";
import { Jost, Geist } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";

const jost = Jost({
  variable: "--font-jost",
  subsets: ['latin']
})

const geist = Geist({
  variable: "--font-geist",
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jost.variable} ${geist.variable} antialiased bg-[#222831] min-h-screen`}
      >
       
       <SessionWrapper>
          <div className="flex">
              <Sidebar></Sidebar>
              <main className="flex-1">
                { children }
              </main>
          </div>
       </SessionWrapper>
     
      </body>
    </html>
  );
}
